### PR TITLE
Add domaintools, domainIQ, tcpiputils, viewdns

### PR DESCRIPTION
**Pull request by ryanmaynard**
Feel free to make description changes as you see fit.

### CODE REVIEW

**Comment by ryanmaynard** [comment]
Good call, @DanielRuf. 

Also, not sure if he intends to add wildcard DNS, but if so:

- http://nip.io/
- http://xip.io/

**Comment by DanielRuf** [comment]
I doubt that xip and nip are checker sevices.

**Comment by ryanmaynard** [comment]
Fair point

**Comment by Brunty** [comment]
@ryanmaynard thanks for this!

@DanielRuf thanks for the input too :)

**Pull request merged**
